### ISSUE TITLE
Test failure due to ExpressMockResponse dependency

### ISSUE THREAD

**Issue by kixxauth** [oddnetworks/oddworks#121]
Stack trace from the CI:

```
Failures:
1) Middleware: Error Handler when error is a plain Object casts error to an Array
  Message:
    TypeError: "list" argument must be an Array of Buffers
  Stack:
    TypeError: "list" argument must be an Array of Buffers
        at Function.Buffer.concat (buffer.js:313:11)
        at MockExpressResponse.MockServerResponse._getString (/home/travis/build/oddnetworks/oddworks/node_modules/mock-res/index.js:55:16)
        at MockExpressResponse.MockServerResponse._getJSON (/home/travis/build/oddnetworks/oddworks/node_modules/mock-res/index.js:59:25)
```

**Comment by kixxauth** [comment]
There is currently a big hack in place to get around this until something happens upstream to fix it:

https://github.com/oddnetworks/oddworks/pull/120

**Comment by kixxauth** [comment]
Reference:

https://github.com/lykmapipo/mock-express-response/issues/3

https://github.com/diachedelic/mock-res/issues/5

**Comment by blainsmith** [comment]
I think I fixed this?
