### ISSUE TITLE
Weird Oddcast handler promise warning

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddworks#17]
@kixxauth Not sure why this is happening, but the everything actually does work it just continues to throw this warning. Am I missing a promise return somewhere? You can see it on this branch https://github.com/oddnetworks/oddworks/tree/service-based-architecture

**Running**

1. Copy `.env.sample` to `.env` so you have good vars
2. `npm run dev` to seed in-memory Redis
3. Grab a JWT from `./data/device/*.json`
4. Toss it in the `x-access-token` header and hit http://127.0.0.1:3000/videos
5. Read da console!

```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at RequestChannel.utils.extend.executeHandler (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/channel.js:171:10)
    at InprocessTransport.onMessage [as handler] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/channel.js:134:18)
    at InprocessTransport.utils.extend.write (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/inprocess_transport.js:26:16)
    at RequestChannel.utils.extend.request (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/request_channel.js:23:20)
    at Bus.utils.extend.query (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/oddcast/lib/bus.js:67:24)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/services/catalog/index.js:35:8
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:46:12)
From previous event:
    at /Users/blainsmith/Projects/oddnetworks/oddworks/services/identity/index.js:34:6
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:312:13)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at compression (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/compression/index.js:218:5)
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:312:13)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at requestSession (/Users/blainsmith/Projects/oddnetworks/oddworks/middleware/request-session.js:10:2)
    at Layer.handle [as handle_request] (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:312:13)
    at /Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/blainsmith/Projects/oddnetworks/oddworks/node_modules/express/lib/router/index.js:271:10)
    at requestContentType (/Users/blainsmith/Projects/oddnetworks/oddworks/middleware/request-accept.js:22:2)
```

**Comment by kixxauth** [comment]
Interesting.

Warning from Bluebird can be turned off (they are automatically turned off when NODE_ENV=production)

I've filed this issue in Oddcast.

https://github.com/oddnetworks/oddcast/issues/21

**Comment by brkattk** [comment]
I could be wrong, but I think this is happening because arrow functions with a block body don't automatically return anything. The warning can be suppressed by returning `null` when we don't care about chaining another promise.

https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

**Comment by kixxauth** [comment]
Yeah, more docs from Bluebird:

http://bluebirdjs.com/docs/warning-explanations.html

JavaScript functions, arrow blocks or not, always return undefined if a return statement is not specified.

Trying to track down where this is happening. I think it is in Oddworks, so reopening here.

**Comment by blainsmith** [comment]
I think this resolved itself in all the recent commits.
