### ISSUE TITLE
identity-login-controller throws 500 instead of 401

### ISSUE THREAD

**Issue by brkattk** [oddnetworks/oddworks#251]
When I try to login with an invalid password, I get the following 500 error:

```
{
	"errors": [{
		"status": "500",
		"title": "TypeError",
		"detail": "Cannot read property 'password' of null"
	}]
}
```

Here's the stack trace:

```
2016-10-28T17:05:10.139959+00:00 app[web.1]: TypeError: Cannot read property 'password' of null
2016-10-28T17:05:10.139973+00:00 app[web.1]:     at /app/node_modules/@oddnetworks/oddworks/lib/services/identity/controllers/identity-login-controller.js:153:53
2016-10-28T17:05:10.139975+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2016-10-28T17:05:10.139976+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31)
2016-10-28T17:05:10.139977+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18)
2016-10-28T17:05:10.139978+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
2016-10-28T17:05:10.139978+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18)
2016-10-28T17:05:10.139979+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:16)
2016-10-28T17:05:10.139980+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10)
2016-10-28T17:05:10.139980+00:00 app[web.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
2016-10-28T17:05:10.139981+00:00 app[web.1]:     at Immediate.instrumented (/app/node_modules/opbeat/lib/instrumentation/index.js:111:27)
2016-10-28T17:05:10.139982+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I think basically any time we create a `Boom` error, we need to immediately pass it to `next` when possible. Otherwise we're catching and re-creating or doing other things.

**Comment by brkattk** [comment]
OK - this is caused due to my moronic use of GET rather than POST. We should probably lock that down better

**Comment by brkattk** [comment]
Here's my login request

```
curl -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGFubmVsIjoibmFzYSIsInBsYXRmb3JtIjoibmFzYS1hbmRyb2lkIiwiYXVkIjpbInBsYXRmb3JtIl0sImlzcyI6InVybjpvZGR3b3JrcyJ9.6a4tEL3hTYGC2Z-iWVp_0aVqx17TKZ37i2F10lPkBRI' -H 'x-odd-user-agent: model[manufacturer]=LGE&model[brand]=google&model[name]=Nexus 5X&model[version]=bullhead&os[name]=7.0&os[version]=24&build[version]=1.0' -H 'accept: application/json' -H 'accept-language: en-us' -H 'Cache-Control: no-cache' -H 'Content-Type: application/json; charset=utf-8' -H 'Host: content.oddworks.io' -H 'User-Agent: okhttp/2.7.5' --data-binary '{"data":{"id":"paul@oddworks.com","type":"authentication","attributes":{"email":"paul@oddworks.com","password":"PaulIsPurple"}}}' --compressed 'https://content.oddworks.io/v2/login'
```

**Comment by blainsmith** [comment]
You have an invalid email. It is paul@**oddnetworks**.com. The error is still wrong and should 401 for an invalid email though.

**Comment by brkattk** [comment]
![derp](https://imgflip.com/s/meme/Derp.jpg)
